# Secrets for Inventory Management System
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  labels:
    app: inventory-management
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  # Username: inventory_user -> aW52ZW50b3J5X3VzZXI=
  # Password: inventory_pass -> aW52ZW50b3J5X3Bhc3M=
  DB_USER: aW52ZW50b3J5X3VzZXI=
  DB_PASSWORD: aW52ZW50b3J5X3Bhc3M=
  POSTGRES_USER: aW52ZW50b3J5X3VzZXI=
  POSTGRES_PASSWORD: aW52ZW50b3J5X3Bhc3M=

---
# Note: To create your own encoded secrets, use:
# echo -n "your-username" | base64
# echo -n "your-password" | base64