# PostgreSQL Deployment for Inventory Management System - Fixed for Minikube
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: inventory-management
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
      component: database
  template:
    metadata:
      labels:
        app: inventory-management
        component: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        
        # Environment variables from ConfigMap and Secrets
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_INITDB_ARGS
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: POSTGRES_INITDB_ARGS
        
        # Volume mounts - Using emptyDir for now (temporary storage)
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        
        # Health check
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - inventory_user
            - -d
            - inventory_db
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - inventory_user
            - -d
            - inventory_db
          initialDelaySeconds: 5
          periodSeconds: 5
        
        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      volumes:
      - name: postgres-storage
        emptyDir: {}  # Temporary storage - data will be lost if pod restarts